name: Tests
on: [push]
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: Build tests
        run: make -C ${{ github.workspace }} test -j16
      - name: Run tests
        run: ${{ github.workspace }}/test.exe